export const CART_SELECTORS = {
    applyCouponButton: '#discount-coupon-form .actions-toolbar button.action.apply',
    cancelCouponButton: '.cart-discount .actions-toolbar button.action.cancel',
    cartEmptyMessage: '.cart-empty',
    cartItem: '.cart.item',
    cartPageProductName: '.product-item-name a',
    cartSummary: '.cart-summary',
    checkoutButton: '#top-cart-btn-checkout',
    checkoutSection: '.checkout-methods-items',
    closeMiniCartButton: '#btn-minicart-close',
    countrySelect: '[name="country_id"]',
    couponBlock: '#block-discount [data-role="title"]',
    couponCodeInput: '.coupon',
    deleteButton: '.action.delete',
    deleteButtonCart: '.action.action-delete',
    editButton: '.action.edit',
    editButtonCart: '.action.action-edit',
    updateActionButton: 'button.action.update',
    itemsTotal: '.items-total .count',
    miniCartItemsWrapper: '#minicart-items-wrapper',
    miniCartToggle: '[data-block="minicart"] .showcart',
    miniCartWrapper: '#minicart-content-wrapper',
    priceWrapper: '.amount .price-wrapper',
    proceedToCheckoutButton: 'li button[data-role="proceed-to-checkout"]',
    productCartOptions: '.item-options',
    productDetails: '.product-item-details',
    productImage: '.product-image-photo',
    productOptions: 'dl.product.options',
    productPrice: '.cart-price .price',
    productQtyInput: 'input.input-text.qty',
    productSubtotal: '.subtotal .price',
    qtyInput: '.item-qty.cart-item-qty',
    qtyInputCart: '[data-role="cart-item-qty"]',
    qtyValue: '.details-qty .value',
    shippingBlockTitle: '#block-shipping [data-role="title"]',
    shippingRateOptions: 'tr.totals.shipping.excl',
    sizeSwatch: '.swatch-attribute.size',
    stateInput: '[name="region"]',
    stateSelect: '[name="region_id"]',
    swatchOption: '[role="option"]',
    updateCartButton: '#product-updatecart-button',
    updateCartForm: '#product_addtocart_form',
    updateMiniCartButton: 'button[title="Update"]',
    updateShoppingCartButton: '[title="Update Shopping Cart"]',
    zipInput: '[name="postcode"]'
};