import { product } from "../helpers/product";

export const CHECKOUT_SELECTORS = {
    addActionButton: '.action.add',
    addNewAddressButton: 'button.action.action-show-popup',
    backActionButton: '.action.back',
    billingAddressDetails: '.billing-address-details',
    billingAddressId: '[name="billing_address_id"]',
    billingBlockTable: '.box.box-billing-address',
    billingInfoSection: '.billing-address-same-as-shipping-block',
    boxItems: '.box-items',
    cityField: '[name="city"]',
    continueButton: '.action.primary.continue',
    continueButtonShipping: '.primary .action.primary.continue',
    countryField: '[name="country_id"]',
    createAccountButton: 'a.action.primary',
    discountSection: '.discount-code',
    emailAddressField: '#customer-email-fieldset [type="email"]',
    firstNameField: '[name="firstname"]',
    itemsInCartSection: '.items-in-cart',
    lastNameField: '[name="lastname"]',
    modalAddress: '.modal-inner-wrap',
    multiCheckoutButton: '.action.multicheckout',
    multiShipTable: '#multiship-addresses-table',
    nextButton: '[data-role="opc-continue"]',
    option: 'option',
    orderReviewTable: '.table-order-review',
    paymentMethodBoxSection: '.box-billing-method',
    paymentMethodSection: '.payment-methods',
    phoneNumberField: '[name="telephone"]',
    placeOrderButton: '.action.primary.checkout',
    placeOrderMultiShipping: '#review-button',
    productDetails: '.product-item-details',
    productOptions: '.product .options',
    productPhoto: '.product-image-wrapper',
    productPrice: '.cart-price',
    productQty: '.details-qty',
    productTitle: '.product-item-name',
    progressBar: 'ul.opc-progress-bar',
    progressBarItem: '.opc-progress-bar-item',
    saveInAddressBookButton: '.field.choice',
    saveActionButton: 'button.action.save',
    sendToList: '.col.address .control',
    sendToListOption: '.col.address select',
    shipHereButton: '.action.primary.action-save-address',
    shippingAddressItem: '.shipping-address-items .shipping-address-item',
    shippingAddressSection: '.checkout-shipping-address',
    shippingBlockTable: '.block.block-shipping',
    shippingInfoSection: '.shipping-information',
    shippingInfoTitle: '.shipping-information-title',
    shippingMethodButton: 'input.radio',
    shippingMethodSection: '.checkout-shipping-method',
    shippingMethodTable: '.table-checkout-shipping-method',
    shippingToSection: '.box-shipping-address',
    stateProvinceField: '[name="region_id"]',
    streetAddressField: '[name="shippingAddress.street.0"]',
    newStreetAddress: '[title="Street Address"]',
    successPage: '.checkout-success p',
    successMultiPage: '.multicheckout.success',
    summarySection: '.opc-block-summary',
    submitActionButton: '.action.primary.submit',
    zipPostalCodeField: '[name="postcode"]',
    qtyMulti: '.field.qty',
    inputQty: 'input[type="number"]',
    productItemsInTable: 'tbody td.product',
    removeItemButton: '.action.delete',
    editActionButton: '.action.edit',
    defaultAddressInfo: '.message.info',
    addressesBlock: '.block.block-billing',
    addressesToChoose: '.box-billing-address',
    actionButton: '.action'
};