export const CHECKOUT_SELECTORS = {
    actionGenericButton: '.action',
    addAddressButton: 'button.action.action-show-popup',
    addItemButton: '.action.add',
    addressesBlock: '.block.block-billing',
    addressesToChoose: '.box-billing-address',
    applyCouponButton: '.action.action-apply',
    backButton: '.action.back',
    billingAddressDetailsSection: '.billing-address-details',
    billingAddressIdField: '[name="billing_address_id"]',
    billingBlock: '.box.box-billing-address',
    billingSameAsShippingSection: '.billing-address-same-as-shipping-block',
    cancelAction: '.action.action-cancel',
    cartItemsSection: '.box-items',
    cityField: '[name="city"]',
    continueButton: '.action.primary.continue',
    countrySelect: '[name="country_id"]',
    couponBlock: '.payment-option-title',
    createAccountButton: 'a.action.primary',
    customerEmailField: '#customer-email-fieldset [type="email"]',
    defaultAddressMessage: '.message.info',
    discountCodeInput: 'input#discount-code',
    discountSection: '.discount-code',
    editAddressButton: '.action.action-edit-address',
    editItemButton: '.action.edit',
    firstNameField: '[name="firstname"]',
    inputQtyField: 'input[type="number"]',
    itemsInCartSection: '.items-in-cart',
    lastNameField: '[name="lastname"]',
    modalAddressWrap: '.modal-inner-wrap',
    multiShippingButton: '.action.multicheckout',
    multiShippingSuccessTYPage: '.multicheckout.success',
    multiShippingTable: '#multiship-addresses-table',
    newStreetAddressField: '[title="Street Address"]',
    nextStepButton: '[data-role="opc-continue"]',
    optionElements: 'option',
    orderReviewTable: '.table-order-review',
    paymentBox: '.box-billing-method',
    paymentMethodsSection: '.payment-methods',
    phoneNumberField: '[name="telephone"]',
    placeOrderButton: '.action.primary.checkout',
    placeOrderMultiShippingButton: '#review-button',
    productImage: '.product-image-wrapper',
    productItemsInTable: 'tbody td.product',
    productOptions: '.product .options',
    productPrice: '.cart-price',
    productQty: '.details-qty',
    productTitle: '.product-item-name',
    progressBar: 'ul.opc-progress-bar',
    progressBarStepItem: '.opc-progress-bar-item',
    qtyFieldMultiShipping: '.field.qty',
    removeItemButton: '.action.delete',
    saveButton: 'button.action.save',
    saveInAddressBookCheckbox: '.field.choice',
    selectBillingAddressDropdown: '[name="billing_address_id"]',
    selectShippingAddressDropdown: '.col.address select',
    sendToListControl: '.col.address .control',
    shipHereButton: '.action.primary.action-save-address',
    shippingAddressItem: '.shipping-address-items .shipping-address-item',
    shippingAddressSection: '.checkout-shipping-address',
    shippingBlock: '.block.block-shipping',
    shippingInfoSection: '.shipping-information',
    shippingInfoTitle: '.shipping-information-title',
    shippingMethodRadio: 'input.radio',
    shippingMethodSection: '.checkout-shipping-method',
    shippingMethodTable: '.table-checkout-shipping-method',
    shippingToSection: '.box-shipping-address',
    stateProvinceSelect: '[name="region_id"]',
    streetAddressField: '[name="shippingAddress.street.0"]',
    submitButton: '.action.primary.submit',
    successTYPage: '.checkout-success p',
    summarySidebarSection: '.opc-block-summary',
    updateItem: '.action-update',
    validationMessageSection: '[data-role="checkout-messages"]',
    zipPostalCodeField: '[name="postcode"]'
};