export const LISTING_SELECTORS = {
    block: '.block',
    compareSection: '#block-compare-heading',
    filterClear: '.filter-clear',
    filterLinks: 'ol li a',
    filterListItem: 'ol li',
    filterOptions: '.filter-options',
    filterOptionsCollapsible: '[data-role="collapsible"]',
    filterOptionsContent: '.filter-options-content',
    filterOptionsItemActive: '.filter-options-item.allow.active',
    filterValue: '.filter-value',
    filtersBlock: '#layered-filter-block',
    gridBlocksHeading: '.content-heading',
    gridWidget: '.widget-product-grid',
    info: 'span.info',
    limiterOptions: '#limiter.limiter-options',
    modeButton: (mode: string) => `a.mode-${mode}`,
    pageTitle: '.page-title',
    productItems: '.product-items',
    productItem: 'li.product-item',
    productsWrapperMode: (mode: string) => `.products.wrapper.${mode}.products-${mode}`,
    sidebarAdditional: '.sidebar-additional',
    sidebarMain: '.sidebar-main',
    sorterOptions: '#sorter.sorter-options',
    swatchAttribute: '.swatch-attribute',
    swatchOption: '.swatch-option',
    toolbarAmount: '.toolbar-amount',
    toolbarNumber: '.toolbar-number',
    toolbarProducts: '.toolbar-products',
    widgetBlocks: '.block-promo',
    wishlistSection: '.block-wishlist'
};