export const NAVIGATION_SELECTORS = {
    billingLastnameField: 'oar-billing-lastname',
    confirmButton: '.modal-inner-wrap button',
    emailField: 'oar_email',
    expandableIcon: (tab: string) => `${NAVIGATION_SELECTORS.tab(tab)} span.ui-menu-icon`,
    footerLinks: 'ul.footer.links a',
    footerPanel: '.footer.links li',
    headerLinks: 'ul.header.links a',
    menuItem: '[role="menuitem"]',
    navigationMenu: '[class="navigation"]',
    navPanel: (nav: string) => nav,
    orderIdField: 'oar-order-id',
    pageTitleHeading: '#page-title-heading',
    privacyPolicyContent: '.privacy-policy-content',
    privacyPolicyNavPanel: '#privacy-policy-nav-content',
    subMenu: 'ul.submenu',
    tab: (tab: string) => `li.category-item:contains(${tab})`,
    title: '.page-title',
    welcomeUserTab: '.customer-welcome .customer-name',
};