export const PRODUCT_SELECTORS = {
    actionButton: (type: 'wishlist' | 'compare') => `.action.to${type}`,
    actionElements: {
        compare: 'a.action.tocompare',
        wishlist: 'a.action.towishlist',
    },
    actionsSecondary: '.actions-secondary',
    activeImage: '.fotorama__stage__frame.fotorama__active img',
    additionalInfoSection: '#additional',
    additionalTab: '#additional',
    addToCart: '.action.tocart',
    addToCartButtonPDP: '#product-addtocart-button',
    addReviewButton: '.reviews-actions .add',
    arrow: (direction: 'prev' | 'next') => `.fotorama__arr--${direction}`,
    compareLink: '.actions-toolbar a.action.compare',
    descriptionTab: '#description',
    descriptionText: '#description',
    galleryPlaceholder: '.gallery-placeholder',
    nicknameField: '#nickname_field',
    pageTitle: 'h1.page-title span',
    productColors: '.swatch-attribute.color',
    productColorOption: '.swatch-attribute.color .swatch-option',
    productComparisonTable: '#product-comparison tr',
    productDetails: '.product.info.detailed',
    productGallery: '.product.media',
    productImage: '.product-image-photo',
    productInfoMain: '.product-info-main',
    productItemDetails: '.product-item-details',
    productMedia: '.product.media',
    productOptionsWrapper: '#product-options-wrapper',
    productPrice: '.normal-price',
    productFinalPrice: '[type="finalPrice"]',
    productReviews: '.rating-result',
    productSize: '.swatch-attribute.size',
    productSizeOption: '.swatch-attribute.size .swatch-option',
    productSku: '.product.attribute.sku .value',
    productStock: '.stock',
    productTitle: '.product-item-name',
    ratingLabel: (rating: number) => `label#Rating_${rating}_label`,
    ratingSummary: '.rating-summary',
    relatedProductsBlock: '.block.related',
    relatedProductsWrapper: '.products-related',
    reviewField: '#review_field',
    reviewItems: '.review-items .review-item',
    reviewsSummary: '.product-reviews-summary',
    reviewsTab: '#reviews',
    reviewsTabActive: '.product.data.items .title.active',
    submitButton: 'button.submit',
    successMessage: '.message-success',
    summaryField: '#summary_field',
    swatchAttribute: (attribute: string) => `.swatch-attribute.${attribute}`,
    swatchOption: '.swatch-option',
    swatchOptionByLabel: (label: string) => `[role="option"][aria-label="${label}"]`,
    thumbnail: '.fotorama__thumb',
    viewReviewCount: '.reviews-actions a.view [itemprop="reviewCount"]'
};